### ISSUE TITLE
Exception: Illegal characters in path - character "

### ISSUE THREAD

**Issue by NazaretSK** [codecoding/PluralSightDownloader#10]
Course: https://app.pluralsight.com/library/courses/sharepoint-2013-client-object-model-rest
Video: Working with Custom and "Legacy" Web Services

![illegal characters in path](https://cloud.githubusercontent.com/assets/5917483/11018823/a39e3f72-85db-11e5-9e18-6a4d489ccea8.jpg)

**Comment by robertohuertasm** [comment]
Hi @NazaretSK, it has been solved in the last commit. Now you should be able to download the video.

**Comment by caminante99** [comment]
/PluralSightDownloader has stopped working/ message.

https://app.pluralsight.com/library/courses/functional-architecture-fsharp/

Chapter: Map/Reduce
videos Map/Reduce Pattern Language

Probably this behabiour is related to the use of illegal characters in file names, in this case with the "/" character.
These are common illegal characters for file names: \ / : " < > * ? |
please remap these illegal chacters to another valid character.
Thanks.

**Comment by robertohuertasm** [comment]
Fixed
