### ISSUE TITLE
Video names

### ISSUE THREAD

**Issue by artlantis** [codecoding/PluralSightDownloader#14]
Is it possible to add course folders in the destination folder?

**Comment by robertohuertasm** [comment]
I'm not sure to understand what you mean...

**Comment by artlantis** [comment]
when we start the download, the application download all videos in the same folder. As you might know, all videos categorized by section in the pluralsight. I mean, the application can create the folders based on the treeview then put the downloaded video in appropiate folder.

**Comment by robertohuertasm** [comment]
I see. I decided not to do that so I could play all the videos one after the other automatically but maybe is a good thing to add. I'll consider this as an enhancement. ;-)

**Comment by Mattiullah** [comment]
also problem with videos name
names like url

**Comment by artlantis** [comment]
Yes, we can use the tree leafs as a video name. Just we need to put order numbers as a prefix, like "01.Introduction" or "12.Summary".

**Comment by robertohuertasm** [comment]
Solved in latest pull request #30
