### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by rahulgarg1985** [codecoding/PluralSightDownloader#15]
Hello,
I was trying to build the solution but it is showing some issue with CefSharp. Although all required packages are in place.

Can you suggest ?

**Comment by robertohuertasm** [comment]
HI @rahulgarg1985, can you be more specific? What kind of error message are you receiving? You have to choose x86 platform when you build... I don't know if that's maybe your problem. 

Please let me know ;D

Best regards,
Roberto.

**Comment by robertohuertasm** [comment]
As I have no feedback from @rahulgarg1985 I proceed to close the issue. Please, let me know if this is still an issue.
