### ISSUE TITLE
Cannot Start Application

### ISSUE THREAD

**Issue by jeffz80** [codecoding/PluralSightDownloader#16]
It shows "You cannot start application from this locationo because it is already installed from a different location" when I click the application from my computer. 

However if I put "https://downloads.codecoding.com/pluralsightdownloader/PluralsightDownloader.Forms.application" in the browser, nothing happens. 

So how does this application work? I'm confused.

**Comment by jeffz80** [comment]
Well, it seems that I can't open PluralsightDownloader.Forms.application. Whenever I click it, nothing happens. Do you have any suggestion about this?

**Comment by robertohuertasm** [comment]
Which browser are you using? Have you tried with Edge or Explorer?

**Comment by robertohuertasm** [comment]
@jeffz80 have you tried this link? [https://downloads.codecoding.com/pluralsightdownloader/publish.htm](https://downloads.codecoding.com/pluralsightdownloader/publish.htm) You should execute the setup.exe file!
