### ISSUE TITLE
Crash when the filename contains not allowed character

### ISSUE THREAD

**Issue by monczszilard** [codecoding/PluralSightDownloader#18]
When the caption contains e.g. * in the title the app will crash.
Just remove the not allowed chars from the filename. Also keep to short enough to not cause path too long errors.

**Comment by robertohuertasm** [comment]
Can you provide the name of the course where you're getting this errors from?

**Comment by monczszilard** [comment]
oracle-database-12c-disaster-recovery-m6-03_moving-data_introducing-sql*loader.mp4

Adding a .Replace("*", "") into GetVideoName fixed the problem.
