### ISSUE TITLE
Program crashes on certain downloads

### ISSUE THREAD

**Issue by chaoscreater** [codecoding/PluralSightDownloader#22]
Hi there,

I've experienced consistent crashes when I try to download this course:
"Windows Server 2012 Remote Desktop Infrastructure"

It doesn't matter if I download a module or the entire course, it crashes after starting the download for a few seconds.

Event log shows this:

>
> Faulting application name: PluralsightDownloader.Forms.exe, version: 1.0.0.0, time stamp: 0x56fd35b1
> Faulting module name: KERNELBASE.dll, version: 10.0.10586.0, time stamp: 0x5632da1c
> Exception code: 0xe0434352
> Fault offset: 0x000bd8a8
> Faulting process id: 0x1f1c
> Faulting application start time: 0x01d18fe258654a11
> Faulting application path: C:\Users\xxxxx\AppData\Local\Apps\2.0\OKTYGZ41.4P3\5AVYXGAT.KMD\plur..tion_aa6a620630c5490b_0001.0000_8049c8a1605fa208\PluralsightDownloader.Forms.exe
> Faulting module path: C:\Windows\SYSTEM32\KERNELBASE.dll
> Report Id: 25c9dbce-dad9-4dc9-85de-a85b353308cf
> Faulting package full name: 
> Faulting package-relative application ID: 
> 

It's also happened to a few other courses I tried to download, but they were easily fixed by just restarting the download. It's not the same for this particular course, no matter what I do it just crashes.

I've tried deleting the entire folder under the path shown in my Event Log, then re-downloaded PluralSight Downloader from your site. Still the same thing.

**Comment by robertohuertasm** [comment]
Solved! :smile:
