### ISSUE TITLE
The App close

### ISSUE THREAD

**Issue by franklinrony** [codecoding/PluralSightDownloader#34]
Hi first at all many thanks for the tool,its very useful. Th tool work fine,but have a issue with some courses. For example this
https://app.pluralsight.com/library/courses/mvc4-building/table-of-contents
when try to download the app close without a warning.
The same troubl for all .asp courses

**Comment by robertohuertasm** [comment]
Solved in #35 
Thanks for reporting the issue! :wink:

**Comment by franklinrony** [comment]
Thank you!!

**Comment by franklinrony** [comment]
A last question. How update the app with the last commit? I need uninstall first?

**Comment by robertohuertasm** [comment]
Reinstalling the application should suffice ;-)


Roberto






On Sat, Apr 23, 2016 at 8:14 PM -0700, "Franklin Rony Cortez" <notifications@github.com> wrote:





A last question. How update the app with the last commit? I need uninstall first?

---
