### ISSUE TITLE
Time between downloads

### ISSUE THREAD

**Issue by ragtimesp** [codecoding/PluralSightDownloader#36]
Does the time between downloads work? I have got my account suspended for a while and according to the person who emailed me they said I was doing requests to the server every 10-30 seconds while I had setup 2 minutes between downloads.

**Comment by robertohuertasm** [comment]
Hi @ragtimesp, I'm sorry to hear that. I've just checked and it seems to be working. Just before every download the thread sleeps for the specified time. The number is in milliseconds so 10000 would be 10s between downloads. 

Where you maybe using several clients at the same time?

**Comment by phuocdat669** [comment]
@ragtimesp Hello.  There must be something wrong because the maximum number you can set is 100000 ms (which is 100 s).  How can you set it to 2 minutes :D

**Comment by ragtimesp** [comment]
@phuocdat669 you are right, didn't realized that it changed the 120000 to 100000. @robertohuertasm not really. I was using just one. At the beginning I thought it would be due to bandwidth as I downloaded several courses, but apparently as they said I was doing requests to the server with that frequency, which seems odd to me.

**Comment by robertohuertasm** [comment]
@ragtimesp @phuocdat669 you were right. The maximum was set to 100000 ms. Now I've set it to 10000000 and default is 30000ms. I thing this will solve the issue. #38
