### ISSUE TITLE
Crashes with message "Length cannot be less than zero"

### ISSUE THREAD

**Issue by Reci** [codecoding/PluralSightDownloader#41]
Hello,
i've got error "Length cannot be less than zero" ("Длина не может быть меньше нуля" in Russian), while downloading ["ASP.NET 3.5 Fundamentals" course](https://app.pluralsight.com/library/courses/aspdotnet-fundamentals/table-of-contents). I've tried 3 times - program always crashes after downloaded _0515_aspdotnet_deployment_Deployment_Summary_ file.
Original error message:

> System.ArgumentOutOfRangeException was unhandled
>Message: An unhandled exception of type 'System.ArgumentOutOfRangeException' occurred in mscorlib.dll
>Additional information: Длина не может быть меньше нуля.

Other courses are downloaded normally.

**Comment by robertohuertasm** [comment]
Hi @Reci, have you tried downloading the module? or does it just happen when you download the whole course? I guess you don't use the Organize in Folders check, do you?

**Comment by robertohuertasm** [comment]
Fixed in #42 
Thanks and best regards!
