### ISSUE TITLE
Feature: Random sleep time

### ISSUE THREAD

**Issue by mvali** [codecoding/PluralSightDownloader#43]
Can you make the time between downloads be the minimum timer sleep (which already exists) and add another field for random sleep time. What I mean is Timer sleep = min value + time between 0 and 20sec (counted in miliseconds) (if user choose 20sec as maximum random sleep time). 
This way will be practically untraceable.
Thank You for everything

**Comment by robertohuertasm** [comment]
Thanks @mvali but I don't really see the point. Take into account that every download takes its own random time so, in the end, it's the same as adding some random time to the sleep time. This would only happen if all videos were the same length and compression format and your connection would be very stable which does not usually happen.

**Comment by mvali** [comment]
Ok I see now. Thank you for clarifying this. 
One question: when app crashes  (Exception Info: System.Net.WebException.. let me know if you need the full error details ) 
and I'm reopening the app Do you make connections to server for each file to check if file has been downloaded (I see activity on my network) or detect by page content?
Thank You for this great app

**Comment by robertohuertasm** [comment]
The check is done in your disk. If you have already downloaded the file the app won't make any download request but you're right and a request is done in order to get the url. This could certainly be optimized :+1:

**Comment by robertohuertasm** [comment]
Solved in #44
