### ISSUE TITLE
Feature Suggestion - Resume

### ISSUE THREAD

**Issue by StealthMicro** [codecoding/PluralSightDownloader#45]
I have a somewhat flaky connection here at home and it causes the PluralSightDownloader to crash from time to time.   It would be great if the app recognized files that were completed and if restarted only downloaded the needed files.

**Comment by robertohuertasm** [comment]
Hi @StealthMicro, this is already implemented. If the file is present in your downloads directory it won't be downloaded again. As I can't know the size of the downloading files in advance (which is related to #46) I cannot know if the integrity of the last downloaded file is ok. At the moment, this would have to be checked manually if some crash would happen. If you see that the video is not ok then you should delete it. The app will begin to download the deleted file.

**Comment by robertohuertasm** [comment]
I've managed to get the file size and provide a system to check existing file integrity. Now, when checking if the file has already been downloaded file size will be taken into account. The method requires a couple of extra request to the server but these requests are light so I guess it's worth it.
